__all__ = ('bytes8', 'bytes16', 'bytes32', 'bytes64', 'uint8', 'uint16', 'uint32', 'uint64')

from typing import NoReturn
from typing_extensions import overload, Literal, final


class _bytes[SelfT: _bytes]:
    @overload
    def __init__(self, data: SelfT): ...

    @overload
    def __init__(self, data: bytes): ...

    def __bytes__(self) -> bytes: ...

    def __getitem__(self, key: int) -> bytes: ...

    def __add__(self, other: bytes) -> bytes: ...

    def __radd__(self, other: bytes) -> bytes: ...


@final
class bytes8(_bytes[bytes8]): ...


@final
class bytes16(_bytes[bytes16]): ...


@final
class bytes32(_bytes[bytes32]): ...


@final
class bytes64(_bytes[bytes64]): ...


class _uint[SelfT: _uint, BytesT: _bytes]:
    class BitsReference:
        def __init__(self) -> NoReturn: ...

        def __getitem__(self, item: int) -> bool: ...

        def __setitem__(self, key: int, value: bool) -> bool: ...

    @overload
    def __init__(self): ...

    @overload
    def __init__(self, data: int): ...

    @overload
    def __init__(self, data: SelfT): ...

    def __bytes__(self) -> bytes: ...

    def __getitem__(self, key: int) -> bytes: ...

    def to_bytes(self, byteorder: Literal["big", "little"]) -> BytesT: ...

    @classmethod
    def from_bytes(cls, data: BytesT, byteorder: Literal["big", "little"]): ...

    def __index__(self) -> int: ...

    def bits(self) -> BitsReference: ...


@final
class uint8(_uint[uint8, bytes8]): ...


@final
class uint16(_uint[uint16, bytes16]): ...


@final
class uint32(_uint[uint32, bytes32]): ...


@final
class uint64(_uint[uint64, bytes64]): ...
