import typing
from typing import NoReturn
from typing_extensions import overload
from typing_extensions import Literal
from typing_extensions import final

__all__ = ['bytes8', 'bytes16', 'bytes32', 'bytes64', 'uint8', 'uint16', 'uint32', 'uint64']

class bytes8:
    @typing.overload
    def __init__(self, data: bytes8) -> None:
        ...
    @typing.overload
    def __init__(self, data: bytes) -> None:
        ...
    def __bytes__(self) -> bytes:
        ...
    def __getitem__(self, arg0: int) -> bytes:
        ...
    def __add__(self, other: bytes) -> object:
        ...
    def __radd__(self, other: bytes) -> object:
        ...
    def __repr__(self) -> str:
        ...
class bytes16:
    @typing.overload
    def __init__(self, data: bytes16) -> None:
        ...
    @typing.overload
    def __init__(self, data: bytes) -> None:
        ...
    def __bytes__(self) -> bytes:
        ...
    def __getitem__(self, arg0: int) -> bytes:
        ...
    def __add__(self, other: bytes) -> object:
        ...
    def __radd__(self, other: bytes) -> object:
        ...
    def __repr__(self) -> str:
        ...
class bytes32:
    @typing.overload
    def __init__(self, data: bytes32) -> None:
        ...
    @typing.overload
    def __init__(self, data: bytes) -> None:
        ...
    def __bytes__(self) -> bytes:
        ...
    def __getitem__(self, arg0: int) -> bytes:
        ...
    def __add__(self, other: bytes) -> object:
        ...
    def __radd__(self, other: bytes) -> object:
        ...
    def __repr__(self) -> str:
        ...
class bytes64:
    @typing.overload
    def __init__(self, data: bytes64) -> None:
        ...
    @typing.overload
    def __init__(self, data: bytes) -> None:
        ...
    def __bytes__(self) -> bytes:
        ...
    def __getitem__(self, arg0: int) -> bytes:
        ...
    def __add__(self, other: bytes) -> object:
        ...
    def __radd__(self, other: bytes) -> object:
        ...
    def __repr__(self) -> str:
        ...
class uint8:
    @typing.overload
    def __init__(self) -> None:
        ...
    @typing.overload
    def __init__(self, data: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    @typing.overload
    def __init__(self, data: int) -> None:
        ...
    @typing.overload
    def __init__(self, data: uint8) -> None:
        ...
    class BitsReference:
        def __getitem__(self, index: int) -> bool:
            ...
        def __setitem__(self, index: int, value: bool) -> bool:
            ...
    def to_bytes(self, byteorder: str = 'big') -> bytes8:
        ...
    @staticmethod
    def from_bytes(data: bytes8, byteorder: str = 'big') -> uint8:
        ...
    def __index__(self) -> int:
        ...
    def bits(self) -> BitsReference:
        ...
    def __repr__(self) -> str:
        ...
    def __ior__(self, other: uint8) -> uint8:
        ...
    def __or__(self, other: uint8) -> uint8:
        ...
    def __eq__(self, other: uint8) -> bool:
        ...
class uint16:
    @typing.overload
    def __init__(self) -> None:
        ...
    @typing.overload
    def __init__(self, data: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    @typing.overload
    def __init__(self, data: int) -> None:
        ...
    @typing.overload
    def __init__(self, data: uint16) -> None:
        ...
    class BitsReference:
        def __getitem__(self, index: int) -> bool:
            ...
        def __setitem__(self, index: int, value: bool) -> bool:
            ...
    def to_bytes(self, byteorder: str = 'big') -> bytes16:
        ...
    @staticmethod
    def from_bytes(data: bytes16, byteorder: str = 'big') -> uint16:
        ...
    def __index__(self) -> int:
        ...
    def bits(self) -> BitsReference:
        ...
    def __repr__(self) -> str:
        ...
    def __ior__(self, other: uint16) -> uint16:
        ...
    def __or__(self, other: uint16) -> uint16:
        ...
    def __eq__(self, other: uint16) -> bool:
        ...
class uint32:
    @typing.overload
    def __init__(self) -> None:
        ...
    @typing.overload
    def __init__(self, data: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    @typing.overload
    def __init__(self, data: int) -> None:
        ...
    @typing.overload
    def __init__(self, data: uint32) -> None:
        ...
    class BitsReference:
        def __getitem__(self, index: int) -> bool:
            ...
        def __setitem__(self, index: int, value: bool) -> bool:
            ...
    def to_bytes(self, byteorder: str = 'big') -> bytes32:
        ...
    @staticmethod
    def from_bytes(data: bytes32, byteorder: str = 'big') -> uint32:
        ...
    def __index__(self) -> int:
        ...
    def bits(self) -> BitsReference:
        ...
    def __repr__(self) -> str:
        ...
    def __ior__(self, other: uint32) -> uint32:
        ...
    def __or__(self, other: uint32) -> uint32:
        ...
    def __eq__(self, other: uint32) -> bool:
        ...
class uint64:
    @typing.overload
    def __init__(self) -> None:
        ...
    @typing.overload
    def __init__(self, data: typing.SupportsInt | typing.SupportsIndex) -> None:
        ...
    @typing.overload
    def __init__(self, data: int) -> None:
        ...
    @typing.overload
    def __init__(self, data: uint64) -> None:
        ...
    class BitsReference:
        def __getitem__(self, index: int) -> bool:
            ...
        def __setitem__(self, index: int, value: bool) -> bool:
            ...
    def to_bytes(self, byteorder: str = 'big') -> bytes64:
        ...
    @staticmethod
    def from_bytes(data: bytes64, byteorder: str = 'big') -> uint64:
        ...
    def __index__(self) -> int:
        ...
    def bits(self) -> BitsReference:
        ...
    def __repr__(self) -> str:
        ...
    def __ior__(self, other: uint64) -> uint64:
        ...
    def __or__(self, other: uint64) -> uint64:
        ...
    def __eq__(self, other: uint64) -> bool:
        ...
__all__ = ('bytes8', 'bytes16', 'bytes32', 'bytes64', 'uint8', 'uint16', 'uint32', 'uint64')
class _bytes:
    def __bytes__(self) -> bytes:
        ...
    def __getitem__(self, key: int) -> bytes:
        ...
    def __add__(self, other: bytes) -> bytes:
        ...
    def __radd__(self, other: bytes) -> bytes:
        ...
class _uint:
    class BitsReference:
        def __init__(self) -> NoReturn:
            ...
        def __getitem__(self, item: int) -> bool:
            ...
        def __setitem__(self, key: int, value: bool) -> bool:
            ...
    def __bytes__(self) -> bytes:
        ...
    def __getitem__(self, key: int) -> bytes:
        ...
    def to_bytes(self, byteorder: Literal['big', 'little']) -> BytesT:
        ...
    @classmethod
    def from_bytes(cls, data: BytesT, byteorder: Literal['big', 'little']) -> None:
        ...
    def __index__(self) -> int:
        ...
    def bits(self) -> BitsReference:
        ...
